### PR TITLE
Person class- Encapsulation

### PR DESCRIPTION
**Pull request by Alexiahincu**

### CODE REVIEW

**Comment by mihai-sarmaru** [comment]
Screenshot 2021-11-17 at 17 08 44

First thing's first - there's an exception thrown when you first start the app. Here's where it happens. I suggest to use a `StringBuilder` instead of the `fileInfo` array.

**Comment by mihai-sarmaru** [comment]
### Person Class
- Extract the `Person` class to a new file named `Person.cs`
- Instead of using public member variables, use public `Properties` to store the information (ex: `public string FirstName { get; set; }`) It's best practice to use Properties.
### Utility Class
- Extract and rename the static `Utility` class to a new file named `PersonHelper.cs`
- Follow best practices and use the following convention `public static ReturnType MethodName` for all methods
- `FindPerson` method should have only one parameter instead of the array -> `searchTerm` for example

**Comment by mihai-sarmaru** [comment]
### Logic Cleanup
- Extract the first switch statement `switch (parts.Length)` to a separate `private` method that returns the command
- Extract `case "add person":` logic to a separate `private` method, and display a message if the command is incorrect (first / last / age) are missing from the command
- Mark all methods and global variables with the correct access modifier. All should be `private` except `Main()`. There's no need to expose the implementation to others.

**Comment by mihai-sarmaru** [comment]
The pull request can be merged!
One optional improvement idea is to refactor a bit the logic inside `PersonHelper.FindPerson` method. It has a bit of code duplication and logic that can be simplified.

**Comment by Alexiahincu** [comment]
Is the FindPerson method ok now?

**Pull request merged**
